apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: prod-issuer
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: origin-key-secret
      key: key
---
apiVersion: v1
kind: Secret
metadata:
  name: origin-key-secret
type: Opaque