apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production-recruiting-frontend

resources:
  - frontend-ingress.yaml
  - frontend-issuer.yaml
  - frontend-cert-manager.yaml
  - deployment.yaml
